name: ci

on: [push, pull_request]

jobs:
  core:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install YAJL
      run: sudo apt-get install -y libyajl-dev
      continue-on-error: true
    - name: Install OpenSSL
      run: sudo apt-get install -y libssl-dev
    - name: Install Reference tasecureapi Implementation
      run: |
        git clone https://github.com/rdkcentral/tasecureapi.git tasecureapi
        cd tasecureapi
        cmake -S reference -B reference/cmake-build
        cmake --build reference/cmake-build
        sudo cmake --install reference/cmake-build
    - name: Config
      run: >-
        cmake
        -S .
        -B cmake-build
    - name: Build
      run: cmake --build cmake-build
    - name: Install
      run: sudo cmake --install cmake-build
